# travis does not use tox because scipy takes long to install
# with pip. It is better to use miniconda
sudo: false

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6  # Minimum
      env:
        - JOB: 'UNITTEST'
        - FULL_DEPS: true
    - python: 3.8  # Maximum
      env:
        - JOB: 'UNITTEST'
        - FULL_DEPS: true
    - python: 3.8
      env:
        - JOB: 'DOCS'
        - FULL_DEPS: true
    - python: 3.8
      env:
        - JOB: 'LINT'
        - FULL_DEPS: false

cache: pip

notifications:
  email: false


# miniconda recipe
# http://conda.pydata.org/docs/travis.html#using-conda-with-travis-ci
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # Dependencies
  - conda create -q -n plydata-test python=$TRAVIS_PYTHON_VERSION
  - source activate plydata-test
  - |
    if [[ "$FULL_DEPS" ]]; then
      conda install pandas
    fi
  - |
    if [[ "$JOB" == "UNITTEST" ]]; then
      conda install pytest-cov
    elif [[ "$JOB" == "DOCS" ]]; then
      pip install sphinx
      python setup.py install
    elif [[ "$JOB" == "LINT" ]]; then
      pip install flake8
    fi
  - pip install coveralls
  # List all conda and pip packages
  - conda list
  - pip list

script:
  - |
    if [[ "$JOB" == "UNITTEST" ]]; then
      coverage erase
      make test
    elif [[ "$JOB" == "DOCS" ]]; then
      pushd doc
      sphinx-build -W -b html -d _build/doctrees . _build/html
      popd
    elif [[ "$JOB" == "LINT" ]]; then
      make lint
    fi

# Calculate coverage
after_success:
  - |
    if [[ "$JOB" == "UNITTEST" ]]; then
      coveralls --rcfile=.coveragerc
    fi

after_failure:
  - |
    if [[ "$JOB" == "DOCS" ]]; then
      cat /tmp/sphinx-err-*.log
    fi
